#!/bin/sh

# Wifi
if [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'up' ] ; then
	wifi="📡 up - $(iw dev wlo1 link | grep 'SSID:' | cut -d' ' -f2-)"
elif [ "$(cat /sys/class/net/w*/operstate 2>/dev/null)" = 'down' ] ; then
	wifi="📡 down"
fi

printf "%s\n" "$wifi"
